import type { Metadata } from "next";
import { Inter, Libre_Franklin } from "next/font/google";
import "./globals.css";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });
const franklin = Libre_Franklin({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Congelados",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={franklin.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
